/**
 * MSW 핸들러 = 실행 가능한 API 명세 (frontend-testing.md — 계약 변경 시 이 파일을 함께 갱신)
 *
 * 기본(성공) 시나리오만 정의 — 개별 테스트는 server.use()로 실패 응답을 덧씌운다.
 * 데이터는 메모리 상수(불변) — 뮤테이션 후 상태 변화를 검증하는 테스트는
 * 핸들러를 재정의해 사용한다.
 */
import { HttpResponse, http } from 'msw'

import type { ApiEnvelope } from '@/api/types'
import { emptyContent, serializeContent } from '@/features/editor/model/content-io'

/** 빈 Canonical 문서 v1 — 상세·생성 응답의 content 초기값 (08-core/02-model.md §1.5.1) */
const EMPTY_CONTENT = serializeContent(emptyContent())

const BASE = ''

export function ok(data: Partial<ApiEnvelope>): ApiEnvelope {
  return {
    header: { isSuccessful: true, resultCode: 'OK', resultMessage: 'OK' },
    ...data,
  }
}

export function fail(resultCode: string, status: number, errors?: ApiEnvelope['errors']) {
  return HttpResponse.json(
    { header: { isSuccessful: false, resultCode, resultMessage: resultCode }, ...(errors ? { errors } : {}) },
    { status },
  )
}

/* ---------- 공통 픽스처 (테스트에서 재사용) ---------- */

export const fixtures = {
  me: {
    userId: '2',
    email: 'bootstrap@example.com',
    name: '부트스트랩 관리자',
    providers: ['github'],
    admin: true,
    createdAt: '2026-01-02T00:00:00Z',
  },
  providers: { totalCount: 1, responses: [{ code: 'github', displayName: 'GitHub' }] },
  myWorkspaces: {
    totalCount: 2,
    responses: [
      {
        workspaceId: '101',
        name: '개인 ERD',
        description: null,
        isDefault: false,
        myRole: 'OWNER',
        memberCount: 1,
      },
      {
        workspaceId: '102',
        name: '결제팀 공용',
        description: '결제 도메인 ERD',
        isDefault: false,
        myRole: 'EDITOR',
        memberCount: 4,
      },
    ],
  },
  databaseTypes: {
    totalCount: 2,
    responses: [
      { code: 'mysql', displayName: 'MySQL' },
      { code: 'postgresql', displayName: 'PostgreSQL' },
    ],
  },
  /** DDL 생성 응답(1.7) — 방언 조립은 core-api 담당, 목업은 고정 스크립트 */
  ddl: {
    sql: [
      '-- 주문 서비스 ERD — PostgreSQL DDL',
      '',
      'CREATE TABLE member (',
      '    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,',
      '    email VARCHAR(255) NOT NULL,',
      '    CONSTRAINT pk_member PRIMARY KEY (id)',
      ');',
    ].join('\n'),
    warnings: [] as { code: string; message: string }[],
    tableCount: 1,
    relationshipCount: 0,
  },
  /** 배포 응답(1.8) — 전체 성공 기본값. 부분 실패는 server.use()로 덧씌운다 */
  deploy: {
    executedCount: 2,
    failedCount: 0,
    statements: [
      {
        sql: 'CREATE TABLE member (\n    id BIGINT NOT NULL,\n    email VARCHAR(255) NOT NULL\n);',
        ok: true,
        error: null,
      },
      {
        sql: 'ALTER TABLE orders ADD CONSTRAINT fk_orders_member FOREIGN KEY (member_id) REFERENCES member (id);',
        ok: true,
        error: null,
      },
    ],
    warnings: [] as { code: string; message: string }[],
  },
  models: {
    totalCount: 2,
    responses: [
      {
        modelId: '501',
        workspaceId: '101',
        name: '주문 서비스 ERD',
        description: '결제 도메인 1차',
        databaseType: 'postgresql',
        version: 3,
        createdBy: { userId: '2', name: '부트스트랩 관리자' },
        createdAt: '2026-09-05T10:00:00Z',
        updatedAt: '2026-09-10T08:30:00Z',
      },
      {
        modelId: '502',
        workspaceId: '101',
        name: '회원 서비스 ERD',
        description: null,
        databaseType: 'mysql',
        version: 1,
        createdBy: { userId: '3', name: 'kim' },
        createdAt: '2026-09-08T02:00:00Z',
        updatedAt: '2026-09-08T02:00:00Z',
      },
    ],
  },
  /** 공유 링크(§1.10) — 기간 있는 링크 1개 + 무제한 링크 1개 */
  shares: {
    totalCount: 2,
    responses: [
      {
        shareId: '901',
        shareToken: 'Sh4reT0ken0fM0del501aaaa',
        startsAt: '2026-09-01T00:00:00Z',
        endsAt: '2026-10-01T00:00:00Z',
        createdAt: '2026-09-10T00:00:00Z',
      },
      {
        shareId: '902',
        shareToken: 'UnL1mitedT0ken0fM0del501bbb',
        startsAt: null,
        endsAt: null,
        createdAt: '2026-09-11T00:00:00Z',
      },
    ],
  },
  /** 공개 공유 문서(§1.10) — 인증 없는 조회 응답 */
  sharedDocument: {
    modelName: '주문 서비스 ERD',
    description: '결제 도메인 1차',
    databaseType: 'postgresql',
    version: 3,
    content: EMPTY_CONTENT,
    startsAt: null,
    endsAt: null,
  },
  /** 공유 갤러리 목록(§1.10.5) — 인증 없는 랜딩 갤러리 응답 (토큰은 위 shares fixture의 활성 링크) */
  sharedGallery: {
    totalCount: 1,
    responses: [
      {
        shareToken: 'Sh4reT0ken0fM0del501aaaa',
        modelName: '주문 서비스 ERD',
        description: '결제 도메인 1차',
        databaseType: 'postgresql',
        updatedAt: '2026-09-15T00:00:00Z',
        sharedAt: '2026-09-10T00:00:00Z',
      },
    ],
  },
  connections: {
    totalCount: 1,
    responses: [
      {
        connectionId: '301',
        workspaceId: '101',
        name: '개발 PG',
        dbmsType: 'postgresql',
        host: 'db.dev.example.com',
        port: 5432,
        databaseName: 'orders',
        schemaName: 'sales',
        username: 'app',
        createdBy: { userId: '2', name: '부트스트랩 관리자' },
        createdAt: '2026-09-10T00:00:00Z',
      },
    ],
  },
  /** 매니지드 루트 인스턴스 (08-core/07) — PostgreSQL·MySQL. MySQL은 database 생략(발급 시 생성) */
  managedInstances: {
    totalCount: 2,
    responses: [
      {
        instanceId: '401',
        displayName: 'Academy PG',
        dbmsType: 'postgresql',
        host: 's3.java21.net',
        port: 8000,
        databaseName: 'crowfoot',
        username: 'crowfoot',
        isActive: true,
        issuedCount: 1,
        createdBy: { userId: '1', name: '시스템 관리자' },
        createdAt: '2026-09-13T00:00:00Z',
      },
      {
        instanceId: '403',
        displayName: 'Academy MySQL',
        dbmsType: 'mysql',
        host: 's4.java21.net',
        port: 13306,
        databaseName: null,
        username: 'root',
        isActive: true,
        issuedCount: 0,
        createdBy: { userId: '1', name: '시스템 관리자' },
        createdAt: '2026-09-14T00:00:00Z',
      },
    ],
  },
  /** 발급 목록 + 요청자 기준 한도 요약 — me(2)가 발급한 cf_u2_d1 1건 */
  managedDatabases: {
    totalCount: 1,
    responses: [
      {
        databaseId: '31',
        instanceId: '401',
        instanceDisplayName: 'Academy PG',
        schemaName: 'cf_u2_d1',
        workspaceId: '101',
        connectionId: '302',
        connectionName: 'Academy PG #1',
        createdBy: { userId: '2', name: '부트스트랩 관리자' },
        createdAt: '2026-09-13T01:00:00Z',
      },
    ],
    limitSummary: [
      { instanceId: '401', displayName: 'Academy PG', isActive: true, limit: 5, used: 1, remaining: 4 },
    ],
  },
  /** 발급 한도(관리자 지정, 워크스페이스 내 사용자당) — PATCH 핸들러가 이 값을 바꾼다 */
  managedIssueLimit: { limit: 5 },
  teams: {
    totalCount: 2,
    responses: [
      {
        teamId: '201',
        name: '결제 플랫폼팀',
        description: null,
        isOwner: true,
        ownerUserId: '2',
        memberCount: 2,
        createdAt: '2026-01-03T00:00:00Z',
      },
      {
        teamId: '202',
        name: '검색 인프라팀',
        description: null,
        isOwner: false,
        ownerUserId: '5',
        memberCount: 4,
        createdAt: '2026-01-08T00:00:00Z',
      },
    ],
  },
  adminDatabaseTypes: {
    totalCount: 2,
    responses: [
      { code: 'mysql', displayName: 'MySQL', isActive: true },
      { code: 'postgresql', displayName: 'PostgreSQL', isActive: true },
    ],
  },
  adminUsers: {
    page: 1,
    size: 20,
    totalPages: 1,
    totalCount: 3,
    responses: [
      {
        userId: '2',
        email: null,
        name: '부트스트랩 관리자',
        identities: [{ provider: 'github', providerUserId: '48239157' }],
        admin: true,
        withdrawnAt: null,
        createdAt: '2026-01-02T00:00:00Z',
      },
      {
        userId: '5',
        email: 'kim@example.com',
        name: '김철수',
        identities: [
          { provider: 'github', providerUserId: '777001' },
          { provider: 'google', providerUserId: '200412' },
        ],
        admin: false,
        withdrawnAt: null,
        createdAt: '2026-01-05T00:00:00Z',
      },
      {
        userId: '6',
        email: 'old@example.com',
        name: '탈퇴한 사용자',
        identities: [{ provider: 'github', providerUserId: '300951' }],
        admin: false,
        withdrawnAt: '2026-02-10T00:00:00Z',
        createdAt: '2026-01-10T00:00:00Z',
      },
    ],
  },
  adminAuditLogs: {
    page: 1,
    size: 20,
    totalPages: 1,
    totalCount: 3,
    responses: [
      {
        id: '118',
        createdAt: '2026-09-12T01:03:00Z',
        actorUserId: '2',
        actorName: '부트스트랩 관리자',
        actorEmail: null,
        action: 'ROLE_UPDATED',
        targetType: 'ROLE',
        targetId: '2',
        detail: { roleName: 'ADMIN' },
        ip: '203.0.113.10',
      },
      {
        id: '117',
        createdAt: '2026-09-12T00:58:00Z',
        actorUserId: null,
        actorName: null,
        actorEmail: null,
        action: 'USER_LOGGED_IN',
        targetType: 'USER',
        targetId: '5',
        detail: { provider: 'github' },
        ip: null,
      },
      {
        id: '116',
        createdAt: '2026-09-12T00:40:00Z',
        actorUserId: '2',
        actorName: '부트스트랩 관리자',
        actorEmail: null,
        action: 'SESSION_REVOKED_BY_ADMIN',
        targetType: 'SESSION',
        targetId: '00000000-0000-0000-0000-000000000001',
        detail: { userId: '6' },
        ip: '203.0.113.10',
      },
    ],
  },
  adminSessions: {
    page: 1,
    size: 20,
    totalPages: 1,
    totalCount: 1,
    responses: [
      {
        sid: '00000000-0000-0000-0000-000000000001',
        createdAt: '2026-01-05T09:00:00Z',
        lastUsedAt: '2026-01-05T12:30:00Z',
        ip: '203.0.113.10',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/128.0.0.0',
      },
    ],
  },
  adminProviders: {
    totalCount: 2,
    responses: [
      { code: 'github', displayName: 'GitHub', isActive: true },
      { code: 'google', displayName: 'Google', isActive: true },
    ],
  },
  adminRoles: {
    totalCount: 4,
    responses: [
      { code: 'OWNER', displayName: '소유자', level: 40 },
      { code: 'EDITOR', displayName: '편집자', level: 30 },
      { code: 'COMMENTER', displayName: '댓글 작성자', level: 20 },
      { code: 'VIEWER', displayName: '조회자', level: 10 },
    ],
  },
}

/* ---------- auth ---------- */

export const handlers = [
  // 공개 — 로그인 버튼 목록
  http.get(`${BASE}/api/v1/core/providers`, () => HttpResponse.json(ok(fixtures.providers))),

  // OAuth 인가 코드 교환
  http.post(`${BASE}/api/v1/auth/oauth2/:provider/token`, () =>
    HttpResponse.json(
      ok({
        response: { accessToken: 'test-access-token', tokenType: 'Bearer', expiresIn: 3600 },
      }),
    ),
  ),

  // Refresh — 쿠키 존재 가정 하 성공
  http.post(`${BASE}/api/v1/auth/refresh-token`, () =>
    HttpResponse.json(
      ok({ response: { accessToken: 'test-refreshed-token', tokenType: 'Bearer', expiresIn: 3600 } }),
    ),
  ),

  // 로그아웃
  http.post(`${BASE}/api/v1/auth/logout`, () => new HttpResponse(null, { status: 204 })),

  /* ---------- core ---------- */

  http.get(`${BASE}/api/v1/core/accounts/me`, () => HttpResponse.json(ok({ response: fixtures.me }))),

  http.get(`${BASE}/api/v1/core/accounts/me/workspaces`, () =>
    HttpResponse.json(ok(fixtures.myWorkspaces)),
  ),

  // 내 팀 목록 — ownedOnly=true면 isOwner 행만
  http.get(`${BASE}/api/v1/core/teams`, ({ request }) => {
    const ownedOnly = new URL(request.url).searchParams.get('ownedOnly') === 'true'
    const matched = ownedOnly
      ? fixtures.teams.responses.filter((team) => team.isOwner)
      : fixtures.teams.responses
    return HttpResponse.json(ok({ totalCount: matched.length, responses: matched }))
  }),

  // 데이터베이스 종류 코드(활성만) — 모델 생성 다이얼로그 드롭다운
  http.get(`${BASE}/api/v1/core/database-types`, () =>
    HttpResponse.json(ok(fixtures.databaseTypes)),
  ),

  // 모델 목록 — keyword는 이름·설명 부분 일치
  http.get(`${BASE}/api/v1/core/workspaces/:workspaceId/models`, ({ request }) => {
    const keyword = new URL(request.url).searchParams.get('keyword')?.toLowerCase() ?? ''
    const matched = fixtures.models.responses.filter(
      (model) =>
        !keyword ||
        model.name.toLowerCase().includes(keyword) ||
        (model.description ?? '').toLowerCase().includes(keyword),
    )
    return HttpResponse.json(ok({ page: 1, size: 100, totalPages: 1, totalCount: matched.length, responses: matched }))
  }),

  // 모델 상세(1.3) — content 포함 전체, 없으면 404
  http.get(`${BASE}/api/v1/core/workspaces/:workspaceId/models/:modelId`, ({ params }) => {
    const matched = fixtures.models.responses.find((model) => model.modelId === params.modelId)
    if (!matched) return fail('MODEL_NOT_FOUND', 404)
    return HttpResponse.json(
      ok({ response: { ...matched, content: EMPTY_CONTENT } }),
    )
  }),

  // 버전 경량 조회(1.9 협업 폴링) — content 없이 version·updatedAt만
  http.get(`${BASE}/api/v1/core/workspaces/:workspaceId/models/:modelId/version`, ({ params }) => {
    const matched = fixtures.models.responses.find((model) => model.modelId === params.modelId)
    if (!matched) return fail('MODEL_NOT_FOUND', 404)
    return HttpResponse.json(
      ok({ response: { version: matched.version, updatedAt: '2026-09-14T05:00:00Z' } }),
    )
  }),

  // 공유 링크 목록(§1.10) — 최근 발급순
  http.get(`${BASE}/api/v1/core/workspaces/:workspaceId/models/:modelId/shares`, () => {
    return HttpResponse.json(ok(fixtures.shares))
  }),

  // 공유 링크 발급(§1.10) — 무제한/기간 지정
  http.post(`${BASE}/api/v1/core/workspaces/:workspaceId/models/:modelId/shares`, async ({ request }) => {
    const body = (await request.json().catch(() => ({}))) as { startsAt?: string | null; endsAt?: string | null }
    return HttpResponse.json(
      ok({
        response: {
          shareId: String(900 + fixtures.shares.responses.length + 1),
          shareToken: `NewT0ken00000000000000${fixtures.shares.responses.length}`,
          startsAt: body.startsAt ?? null,
          endsAt: body.endsAt ?? null,
          createdAt: '2026-09-15T00:00:00Z',
        },
      }),
      { status: 201 },
    )
  }),

  // 공유 링크 철회(§1.10) — 204
  http.delete(`${BASE}/api/v1/core/workspaces/:workspaceId/models/:modelId/shares/:shareId`, () => {
    return new HttpResponse(null, { status: 204 })
  }),

  // 공유 문서 공개 조회(§1.10) — 인증 없음. expired 토큰은 410, 그 외 없는 토큰은 404
  http.get(`${BASE}/api/v1/core/shares/:token`, ({ params }) => {
    if (params.token === 'expired0000000000000000') return fail('SHARE_INACTIVE', 410)
    if (!fixtures.shares.responses.some((share) => share.shareToken === params.token)) {
      return fail('SHARE_NOT_FOUND', 404)
    }
    return HttpResponse.json(ok({ response: fixtures.sharedDocument }))
  }),

  // 공유 갤러리 목록(§1.10.5) — 인증 없음. 랜딩 페이지가 현재 공유 중인 문서를 나열
  http.get(`${BASE}/api/v1/core/shares`, () => HttpResponse.json(ok(fixtures.sharedGallery))),

  // 모델 생성 — 이름 중복 409, 응답은 생성 리소스(content 포함)
  http.post(`${BASE}/api/v1/core/workspaces/:workspaceId/models`, async ({ request }) => {
    const body = (await request.json()) as { name?: string; databaseType?: string }
    if (fixtures.models.responses.some((model) => model.name === body.name)) {
      return fail('DUPLICATED_NAME', 409)
    }
    return HttpResponse.json(
      ok({
        response: {
          modelId: String(500 + fixtures.models.responses.length + 1),
          workspaceId: '101',
          name: body.name,
          description: null,
          databaseType: body.databaseType,
          content: EMPTY_CONTENT,
          version: 0,
          createdBy: { userId: '2', name: '부트스트랩 관리자' },
          createdAt: '2026-09-12T00:00:00Z',
          updatedAt: '2026-09-12T00:00:00Z',
        },
      }),
      { status: 201 },
    )
  }),

  // 모델 메타 변경 — 이름·설명, 갱신된 메타 반환(픽스처 불변 유지)
  http.patch(`${BASE}/api/v1/core/workspaces/:workspaceId/models/:modelId`, async ({ request }) => {
    const body = (await request.json()) as { name?: string; description?: string | null }
    const matched = fixtures.models.responses[0]
    return HttpResponse.json(
      ok({
        response: {
          ...matched,
          name: body.name ?? matched.name,
          description: body.description !== undefined ? body.description : matched.description,
        },
      }),
    )
  }),

  // 문서 본체 저장(1.5) — baseVersion 불일치 409. 픽스처는 불변, 버전은 계산해 반환
  http.put(`${BASE}/api/v1/core/workspaces/:workspaceId/models/:modelId/content`, async ({ params, request }) => {
    const matched = fixtures.models.responses.find((model) => model.modelId === params.modelId)
    if (!matched) return fail('MODEL_NOT_FOUND', 404)
    const body = (await request.json()) as { baseVersion?: unknown; content?: unknown }
    if (typeof body.baseVersion !== 'number' || typeof body.content !== 'string' || body.content.length === 0) {
      return fail('INVALID_REQUEST', 400)
    }
    if (body.baseVersion !== matched.version) return fail('VERSION_CONFLICT', 409)
    return HttpResponse.json(
      ok({ response: { version: matched.version + 1, updatedAt: '2026-09-12T06:00:00Z' } }),
    )
  }),

  // DDL 스크립트 생성(1.7) — 경고 분기가 필요한 테스트는 server.use()로 덧씌운다
  http.get(`${BASE}/api/v1/core/workspaces/:workspaceId/models/:modelId/ddl`, ({ params }) => {
    const matched = fixtures.models.responses.find((model) => model.modelId === params.modelId)
    if (!matched) return fail('MODEL_NOT_FOUND', 404)
    return HttpResponse.json(ok({ response: fixtures.ddl }))
  }),

  // 포워드 엔지니어링 배포(1.8) — 부분 실패 리포트가 필요한 테스트는 server.use()로 덧씌운다
  http.post(`${BASE}/api/v1/core/workspaces/:workspaceId/models/:modelId/deploy`, async ({ request }) => {
    const body = (await request.json()) as { connectionId?: string }
    const matched = fixtures.connections.responses.find(
      (connection) => connection.connectionId === body.connectionId,
    )
    if (!matched) return fail('CONNECTION_NOT_FOUND', 404)
    return HttpResponse.json(ok({ response: fixtures.deploy }))
  }),

  // 모델 삭제 — 204
  http.delete(`${BASE}/api/v1/core/workspaces/:workspaceId/models/:modelId`, () =>
    new HttpResponse(null, { status: 204 }),
  ),

  /* ---------- DB 커넥션 (08-core/06-connection.md §3) ---------- */

  // 커넥션 목록 — 비밀번호는 내려오지 않는다
  http.get(`${BASE}/api/v1/core/workspaces/:workspaceId/connections`, () =>
    HttpResponse.json(ok(fixtures.connections)),
  ),

  // 커넥션 등록 — 응답에 비밀번호 없음
  http.post(`${BASE}/api/v1/core/workspaces/:workspaceId/connections`, async ({ request }) => {
    const body = (await request.json()) as { name?: string; dbmsType?: string }
    if (!body.name || !body.dbmsType) return fail('INVALID_REQUEST', 400)
    return HttpResponse.json(
      ok({
        response: {
          connectionId: String(600 + fixtures.connections.responses.length + 1),
          workspaceId: '101',
          name: body.name,
          dbmsType: body.dbmsType,
          host: 'db.dev.example.com',
          port: 5432,
          databaseName: 'orders',
          username: 'app',
          createdBy: { userId: '2', name: '부트스트랩 관리자' },
          createdAt: '2026-09-12T00:00:00Z',
        },
      }),
      { status: 201 },
    )
  }),

  // 커넥션 변경 — 변경분 반영(픽스처 불변 유지)
  http.patch(`${BASE}/api/v1/core/workspaces/:workspaceId/connections/:connectionId`, async ({ request, params }) => {
    const matched = fixtures.connections.responses.find(
      (connection) => connection.connectionId === params.connectionId,
    )
    if (!matched) return fail('CONNECTION_NOT_FOUND', 404)
    const body = (await request.json()) as Record<string, unknown>
    return HttpResponse.json(
      ok({ response: { ...matched, ...(body.password ? {} : body) } }),
    )
  }),

  // 커넥션 삭제 — 204
  http.delete(`${BASE}/api/v1/core/workspaces/:workspaceId/connections/:connectionId`, () =>
    new HttpResponse(null, { status: 204 }),
  ),

  // 접속 테스트 — 성공 계약(connected/latencyMs). 실패 시나리오는 server.use()로
  http.post(`${BASE}/api/v1/core/workspaces/:workspaceId/connections/:connectionId/test`, () =>
    HttpResponse.json(ok({ response: { connected: true, latencyMs: 42, message: null } })),
  ),

  // 리버스 엔지니어링 — 신규 문서(빈 캔버스 content) + 요약. 실패는 server.use()로
  http.post(
    `${BASE}/api/v1/core/workspaces/:workspaceId/connections/:connectionId/reverse-engineering`,
    async ({ request, params }) => {
      const matched = fixtures.connections.responses.find(
        (connection) => connection.connectionId === params.connectionId,
      )
      if (!matched) return fail('CONNECTION_NOT_FOUND', 404)
      const body = (await request.json().catch(() => ({}))) as {
        modelName?: string
        description?: string
      }
      const name = body.modelName || `${matched.name} ERD`
      if (fixtures.models.responses.some((model) => model.name === name)) {
        return fail('DUPLICATED_NAME', 409)
      }
      return HttpResponse.json(
        ok({
          response: {
            model: {
              modelId: String(700 + fixtures.models.responses.length + 1),
              workspaceId: '101',
              name,
              description: body.description ?? null,
              databaseType: matched.dbmsType,
              content: EMPTY_CONTENT,
              version: 0,
              createdBy: { userId: '2', name: '부트스트랩 관리자' },
              createdAt: '2026-09-12T00:00:00Z',
              updatedAt: '2026-09-12T00:00:00Z',
            },
            tableCount: 2,
            relationshipCount: 1,
            skipped: [],
          },
        }),
        { status: 201 },
      )
    },
  ),

  /* ---------- core admin (08-core/05-account.md Section 2) ---------- */

  // 사용자 목록 — keyword는 이름·이메일 부분 일치(대소문자 무시)로 반영
  http.get(`${BASE}/api/v1/core/admin/users`, ({ request }) => {
    const keyword = new URL(request.url).searchParams.get('keyword')?.toLowerCase() ?? ''
    const matched = fixtures.adminUsers.responses.filter(
      (user) =>
        !keyword ||
        user.name.toLowerCase().includes(keyword) ||
        (user.email ?? '').toLowerCase().includes(keyword),
    )
    return HttpResponse.json(
      ok({
        page: 1,
        size: 20,
        totalPages: 1,
        totalCount: matched.length,
        responses: matched,
      }),
    )
  }),

  // 사용자 상세 — 없는 userId는 404(존재 은닉)
  http.get(`${BASE}/api/v1/core/admin/users/:userId`, ({ params }) => {
    const user = fixtures.adminUsers.responses.find((row) => row.userId === params.userId)
    return user
      ? HttpResponse.json(ok({ response: user }))
      : fail('RESOURCE_NOT_FOUND', 404)
  }),

  // 활성 세션 목록 — 대상 사용자와 무관하게 항상 같은 페이지
  http.get(`${BASE}/api/v1/core/admin/sessions`, () =>
    HttpResponse.json(ok(fixtures.adminSessions)),
  ),

  // 세션 폐기 — 성공 204 (이미 종료된 sid는 개별 테스트가 server.use로 404를 덧씌운다)
  http.delete(`${BASE}/api/v1/core/admin/sessions/:sid`, () =>
    new HttpResponse(null, { status: 204 }),
  ),

  // 관리자 — 데이터베이스 종류 코드
  http.get(`${BASE}/api/v1/core/admin/database-types`, () =>
    HttpResponse.json(ok(fixtures.adminDatabaseTypes)),
  ),

  http.patch(`${BASE}/api/v1/core/admin/database-types`, async ({ request }) => {
    const body = (await request.json()) as { code: string; displayName?: string; isActive?: boolean }
    const matched = fixtures.adminDatabaseTypes.responses.find((type) => type.code === body.code)
    if (!matched) return fail('RESOURCE_NOT_FOUND', 404)
    if (body.displayName !== undefined) matched.displayName = body.displayName
    if (body.isActive !== undefined) matched.isActive = body.isActive
    return HttpResponse.json(ok({ response: matched }))
  }),

  http.get(`${BASE}/api/v1/core/admin/providers`, () =>
    HttpResponse.json(ok(fixtures.adminProviders)),
  ),

  // 제공자 수정 — 수정된 행 1건 반환
  http.patch(`${BASE}/api/v1/core/admin/providers`, async ({ request }) => {
    const body = (await request.json()) as { code: string; displayName?: string; isActive?: boolean }
    const provider = fixtures.adminProviders.responses.find((row) => row.code === body.code)
    return provider
      ? HttpResponse.json(
          ok({
            response: {
              ...provider,
              ...(body.displayName !== undefined ? { displayName: body.displayName } : {}),
              ...(body.isActive !== undefined ? { isActive: body.isActive } : {}),
            },
          }),
        )
      : fail('RESOURCE_NOT_FOUND', 404)
  }),

  http.get(`${BASE}/api/v1/core/admin/roles`, () => HttpResponse.json(ok(fixtures.adminRoles))),

  // 역할 수정 — 표시명만, 수정된 행 1건 반환
  // 감사 로그 — keyword는 주체(이름·이메일) 부분 일치, action은 정확 일치. 시스템 행은 keyword 있으면 제외
  http.get(`${BASE}/api/v1/core/admin/audit-logs`, ({ request }) => {
    const params = new URL(request.url).searchParams
    const keyword = params.get('keyword')?.toLowerCase() ?? ''
    const action = params.get('action') ?? ''
    const matched = fixtures.adminAuditLogs.responses.filter(
      (log) =>
        (!action || log.action === action) &&
        (!keyword ||
          (log.actorName ?? '').toLowerCase().includes(keyword) ||
          (log.actorEmail ?? '').toLowerCase().includes(keyword)),
    )
    return HttpResponse.json(
      ok({
        page: 1,
        size: 20,
        totalPages: 1,
        totalCount: matched.length,
        responses: matched,
      }),
    )
  }),

  http.patch(`${BASE}/api/v1/core/admin/roles`, async ({ request }) => {
    const body = (await request.json()) as { code: string; displayName?: string }
    const role = fixtures.adminRoles.responses.find((row) => row.code === body.code)
    return role
      ? HttpResponse.json(
          ok({
            response: {
              ...role,
              ...(body.displayName !== undefined ? { displayName: body.displayName } : {}),
            },
          }),
        )
      : fail('RESOURCE_NOT_FOUND', 404)
  }),

  /* ---------- core managed (08-core/07-managed-database.md) ---------- */

  // 관리자 — 인스턴스 목록
  http.get(`${BASE}/api/v1/core/admin/managed-instances`, () =>
    HttpResponse.json(ok(fixtures.managedInstances)),
  ),

  // 관리자 — 발급 한도(워크스페이스 내 사용자당). :instanceId 핸들러보다 먼저 등록해 우선 매칭시킨다
  http.get(`${BASE}/api/v1/core/admin/managed-instances/issue-limit`, () =>
    HttpResponse.json(ok({ response: fixtures.managedIssueLimit })),
  ),
  http.patch(`${BASE}/api/v1/core/admin/managed-instances/issue-limit`, async ({ request }) => {
    const body = (await request.json()) as { limit?: number }
    fixtures.managedIssueLimit.limit = body.limit ?? 5
    return HttpResponse.json(ok({ response: fixtures.managedIssueLimit }))
  }),

  // 관리자 — 인스턴스 등록(자격 검증은 서버 담당, 목업은 성공만) — 201. 제출 값 반영
  http.post(`${BASE}/api/v1/core/admin/managed-instances`, async ({ request }) => {
    const body = (await request.json()) as {
      displayName?: string
      dbmsType?: string
      host?: string
      port?: number
      databaseName?: string | null
      username?: string
    }
    return HttpResponse.json(
      ok({
        response: {
          instanceId: '402',
          displayName: body.displayName ?? '',
          dbmsType: body.dbmsType ?? 'postgresql',
          host: body.host ?? 'db.example.com',
          port: body.port ?? 5432,
          databaseName: body.databaseName ?? null,
          username: body.username ?? 'crowfoot',
          isActive: true,
          issuedCount: 0,
          createdBy: { userId: '1', name: '시스템 관리자' },
          createdAt: '2026-09-14T00:00:00Z',
        },
      }),
      { status: 201 },
    )
  }),

  // 관리자 — 인스턴스 변경 — 수정된 행 1건 반환
  http.patch(`${BASE}/api/v1/core/admin/managed-instances/:instanceId`, async ({ request, params }) => {
    const body = (await request.json()) as Record<string, unknown>
    const matched = fixtures.managedInstances.responses.find(
      (row) => row.instanceId === params.instanceId,
    )
    if (!matched) return fail('MANAGED_INSTANCE_NOT_FOUND', 404)
    Object.assign(matched, body)
    return HttpResponse.json(ok({ response: matched }))
  }),

  // 관리자 — 인스턴스 접속 테스트 — 실패도 200 계약(개별 테스트가 덧씌운다)
  http.post(`${BASE}/api/v1/core/admin/managed-instances/:instanceId/test`, () =>
    HttpResponse.json(
      ok({ response: { connected: true, latencyMs: 41, message: null } }),
    ),
  ),

  // 관리자 — 인스턴스 삭제 — 성공 204 (발급 존재 시 409는 개별 테스트가 덧씌운다)
  http.delete(`${BASE}/api/v1/core/admin/managed-instances/:instanceId`, () =>
    new HttpResponse(null, { status: 204 }),
  ),

  // 사용자 — 발급 목록 + 한도 요약
  http.get(`${BASE}/api/v1/core/workspaces/:workspaceId/managed-databases`, () =>
    HttpResponse.json(ok(fixtures.managedDatabases)),
  ),

  // 사용자 — 발급 — 201 + 발급 상세(스키마·자동 등록 커넥션)
  http.post(`${BASE}/api/v1/core/workspaces/:workspaceId/managed-databases`, async ({ request }) => {
    const body = (request.headers.get('content-length') !== '0'
      ? ((await request.json().catch(() => ({}))) as { instanceId?: string })
      : {}) as { instanceId?: string }
    if (body.instanceId && body.instanceId !== '401') {
      return fail('MANAGED_INSTANCE_NOT_FOUND', 404)
    }
    return HttpResponse.json(
      ok({
        response: {
          databaseId: '32',
          instanceId: '401',
          instanceDisplayName: 'Academy PG',
          schemaName: 'cf_u2_d2',
          workspaceId: '101',
          connectionId: '303',
          connectionName: 'Academy PG #2',
          createdBy: { userId: '2', name: '부트스트랩 관리자' },
          createdAt: '2026-09-14T00:00:00Z',
        },
      }),
      { status: 201 },
    )
  }),

  // 사용자 — 철회 — 성공 204
  http.delete(`${BASE}/api/v1/core/workspaces/:workspaceId/managed-databases/:databaseId`, () =>
    new HttpResponse(null, { status: 204 }),
  ),

  // 사용자 — 발급 접속 정보(본인 발급만) — 발급 31(Academy PG)에 대한 PG 매핑 자격.
  // 자격은 전용 계정(계정명 = 스키마명)이다 — 인스턴스 루트 자격은 노출되지 않는다
  http.get(
    `${BASE}/api/v1/core/workspaces/:workspaceId/managed-databases/:databaseId/credential`,
    ({ params }) => {
      if (params.databaseId !== '31') {
        return fail('MANAGED_DATABASE_NOT_FOUND', 404)
      }
      return HttpResponse.json(
        ok({
          response: {
            databaseId: '31',
            instanceDisplayName: 'Academy PG',
            dbmsType: 'postgresql',
            host: 's3.java21.net',
            port: 8000,
            databaseName: 'crowfoot',
            schemaName: 'cf_u2_d1',
            username: 'cf_u2_d1',
            password: 'Xk9!vQ2mZR7#pLw4nTaE',
          },
        }),
      )
    },
  ),
]
