/**
 * SQL 스크립트 미리보기 다이얼로그 — API 응답 표시·클립보드 복사·파일 다운로드·경고 (05-editor/04-dbms-engineering.md §3.1)
 *
 * 생성은 core-api DDL API(§1.7) — MSW 목업 응답을 그려준다.
 * 클립보드·Blob URL은 브라우저 API라 mock으로 갈음한다.
 */
import { fireEvent, screen, waitFor } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { http, HttpResponse } from 'msw'

import { server } from '@/api/mocks/server'
import { SqlPreviewDialog } from '@/features/editor/components/SqlPreviewDialog'
import { createTable } from '@/features/editor/model/changes'
import { emptyContent } from '@/features/editor/model/content-io'
import { resetEditorStore, useEditorStore } from '@/features/editor/store/editor-store'
import { renderWithProviders } from '@/test/test-app'

afterEach(() => {
  resetEditorStore()
  vi.restoreAllMocks()
})

/** 스토어는 modelId·dirty 판정에만 쓴다 — 문서 내용은 서버 응답 기준 */
function seedStore(): void {
  const content = emptyContent()
  useEditorStore.getState().hydrate({
    modelId: '501',
    baseVersion: 1,
    document: { model: content.model, diagram: content.diagram },
  })
}

function renderDialog(dbmsId = 'postgres', canEdit = true) {
  return renderWithProviders(
    <SqlPreviewDialog
      open
      onOpenChange={vi.fn()}
      workspaceId="101"
      modelName="주문 서비스 ERD"
      dbmsId={dbmsId}
      databaseType={dbmsId === 'common' ? 'oracle' : 'postgresql'}
      canEdit={canEdit}
    />,
    { wrapRoutes: false },
  )
}

describe('SqlPreviewDialog — 미리보기', () => {
  it('문서명·DBMS·API가 생성한 스크립트를 표시한다', async () => {
    seedStore()
    renderDialog()

    // 스크립트가 그려질 때까지 기다린 뒤 나머지를 단언한다 — 생성은 API 응답 기준
    await screen.findByTestId('ddl-script')
    expect(screen.getByText('SQL 스크립트')).toBeVisible()
    expect(screen.getByText('주문 서비스 ERD')).toBeVisible()
    expect(screen.getByText('PostgreSQL')).toBeVisible()
    expect(screen.getByText('테이블 1개 · 관계 0개')).toBeVisible()

    const script = screen.getByTestId('ddl-script').textContent ?? ''
    expect(script).toContain('-- 주문 서비스 ERD — PostgreSQL DDL')
    expect(script).toContain('CREATE TABLE member (')
    expect(script).toContain('id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY')
    expect(script).toContain('CONSTRAINT pk_member PRIMARY KEY (id)')
  })

  it('경고 응답이면 스크립트 앞에 목록을 먼저 표시한다', async () => {
    seedStore()
    server.use(
      http.get('/api/v1/core/workspaces/101/models/501/ddl', () =>
        HttpResponse.json({
          header: { isSuccessful: true, resultCode: 'OK', resultMessage: 'OK' },
          response: {
            sql: '-- DDL',
            warnings: [
              { code: 'COMMON_DIALECT', message: '이 문서의 DBMS는 SQL 방언이 등록되지 않아 공용(논리) 표기로 생성했습니다' },
            ],
            tableCount: 1,
            relationshipCount: 0,
          },
        }),
      ),
    )
    renderDialog('common')

    expect(await screen.findByText('생성 시 주의')).toBeVisible()
    expect(screen.getByText(/공용\(논리\) 표기로 생성했습니다/)).toBeVisible()
  })

  it('실패 응답이면 안내·다시 시도를 표시한다', async () => {
    seedStore()
    server.use(
      http.get('/api/v1/core/workspaces/101/models/501/ddl', () =>
        HttpResponse.json(
          { header: { isSuccessful: false, resultCode: 'MODEL_NOT_FOUND', resultMessage: 'MODEL_NOT_FOUND' } },
          { status: 404 },
        ),
      ),
    )
    renderDialog()

    expect(await screen.findByText('SQL 스크립트 생성에 실패했습니다')).toBeVisible()
    expect(screen.getByRole('button', { name: '다시 시도' })).toBeVisible()
  })

  it('저장되지 않은 변경이 있으면 마지막 저장 본문 기준임을 안내한다', async () => {
    seedStore()
    // hydrate 뒤 커밋 1건 — dirty 상태
    useEditorStore.getState().commit({
      type: 'table/create',
      table: createTable('member'),
      position: { x: 0, y: 0 },
    })
    renderDialog()

    await screen.findByTestId('ddl-script')
    expect(screen.getByText(/마지막 저장 본문 기준입니다/)).toBeVisible()
  })
})

describe('SqlPreviewDialog — 복사·다운로드', () => {
  it('복사 버튼 — 스크립트 전문을 클립보드에 넣는다', async () => {
    seedStore()
    const writeText = vi.fn().mockResolvedValue(undefined)
    Object.assign(navigator, { clipboard: { writeText } })
    renderDialog()

    await screen.findByTestId('ddl-script')
    fireEvent.click(screen.getByRole('button', { name: '복사' }))
    await waitFor(() => expect(writeText).toHaveBeenCalledTimes(1))
    expect(writeText.mock.calls[0][0]).toContain('CREATE TABLE member')
  })

  it('다운로드 버튼 — 문서명.sql Blob을 내려보낸다', async () => {
    seedStore()
    const createObjectURL = vi.fn(() => 'blob:mock')
    const revokeObjectURL = vi.fn()
    Object.assign(URL, { createObjectURL, revokeObjectURL })
    let downloadedName = ''
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(function handleClick(
      this: HTMLAnchorElement,
    ) {
      downloadedName = this.download
    })

    renderDialog()
    await screen.findByTestId('ddl-script')
    fireEvent.click(screen.getByRole('button', { name: '다운로드' }))

    await waitFor(() => expect(createObjectURL).toHaveBeenCalledTimes(1))
    // 파일명은 문서명의 공백을 정리한 값 — 경로에 쓸 수 없는 문자가 없어야 한다
    expect(downloadedName).toBe('주문_서비스_ERD.sql')
  })
})

describe('SqlPreviewDialog — 닫기', () => {
  it('닫기 버튼으로 onOpenChange(false)를 알린다', async () => {
    seedStore()
    const onOpenChange = vi.fn()
    renderWithProviders(
      <SqlPreviewDialog
        open
        onOpenChange={onOpenChange}
        workspaceId="101"
        modelName="주문 서비스 ERD"
        dbmsId="mysql"
        databaseType="mysql"
        canEdit={false}
      />,
      { wrapRoutes: false },
    )

    fireEvent.click(await screen.findByRole('button', { name: '닫기' }))
    expect(onOpenChange).toHaveBeenCalledWith(false)
  })
})

describe('SqlPreviewDialog — 배포 진입', () => {
  it('배포 버튼으로 배포 다이얼로그를 연다 (1.8)', async () => {
    seedStore()
    renderDialog()

    // 스크립트가 도착해야 배포 버튼이 활성화된다
    await screen.findByTestId('ddl-script')
    fireEvent.click(screen.getByRole('button', { name: '배포' }))

    expect(await screen.findByText('데이터베이스에 배포')).toBeVisible()
    expect(screen.getByText(/‘주문 서비스 ERD’ 문서의 DDL을/)).toBeVisible()
  })

  it('읽기 전용 문서에는 배포 버튼이 없다 — 배포는 Editor 이상', async () => {
    seedStore()
    renderDialog('postgres', false)

    await screen.findByTestId('ddl-script')
    expect(screen.queryByRole('button', { name: '배포' })).not.toBeInTheDocument()
  })
})
